In [2]:
import pandas as pd
df1 = pd.DataFrame({
    "Id":[1,2,3],
    "Name":["Tony","Steve","Thor"]
})
                  
df2 = pd.DataFrame({
    "Id":[4,5,6],
    "Name":["Hulk","Spider-Man","Vision"]
})

pd.concat([df1,df2])

   Id        Name
0   1        Tony
1   2       Steve
2   3        Thor
0   4        Hulk
1   5  Spider-Man
2   6      Vision

In [ ]:
pd.concat([df1,df2],ignore_index=True)

   Id        Name
0   1        Tony
1   2       Steve
2   3        Thor
3   4        Hulk
4   5  Spider-Man
5   6      Vision

In [5]:
pd.concat([df1,df2],axis=1)

   Id   Name  Id        Name
0   1   Tony   4        Hulk
1   2  Steve   5  Spider-Man
2   3   Thor   6      Vision